// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa055fff-7961-4e70-847f-4afb90a2d8ac"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 525, DateTimeKind.Local).AddTicks(815),
                            IsDeleted = false,
                            Name = "Book 1",
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(5357)
                        },
                        new
                        {
                            Id = new Guid("0ab852ce-9a81-4ee7-80dc-0af3f465657a"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6165),
                            IsDeleted = false,
                            Name = "Book 2",
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6171)
                        },
                        new
                        {
                            Id = new Guid("a777ab97-019c-47a7-b178-5ad62d3b9fd2"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6175),
                            IsDeleted = false,
                            Name = "Book 3",
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6177)
                        },
                        new
                        {
                            Id = new Guid("034441e8-13e9-47a2-9a98-1a60ddcbf081"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6180),
                            IsDeleted = false,
                            Name = "Book 4",
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6181)
                        },
                        new
                        {
                            Id = new Guid("1144b90a-678d-41bc-ab63-e489c7566dfa"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6184),
                            IsDeleted = true,
                            Name = "Book 5",
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 526, DateTimeKind.Local).AddTicks(6185)
                        });
                });

            modelBuilder.Entity("Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Password")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ffb9c802-865a-4517-994b-76ff2d010e9a"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(8216),
                            IsDeleted = false,
                            Name = "User 1",
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(8822),
                            Username = "user.1"
                        },
                        new
                        {
                            Id = new Guid("182ea661-be2e-4c2e-9373-c9c4e604d36a"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9890),
                            IsDeleted = false,
                            Name = "User 2",
                            Role = 1,
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9898),
                            Username = "user.2"
                        },
                        new
                        {
                            Id = new Guid("0bfd8d12-c569-47b6-8270-bc16e4c5b470"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9903),
                            IsDeleted = false,
                            Name = "User 3",
                            Role = 2,
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9905),
                            Username = "user.3"
                        },
                        new
                        {
                            Id = new Guid("73e1a2a7-5d0e-4c3d-81d6-b7dc72c5c84f"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9909),
                            IsDeleted = false,
                            Name = "User 4",
                            Role = 2,
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9911),
                            Username = "user.4"
                        },
                        new
                        {
                            Id = new Guid("fe82d001-7060-4e29-b037-bf21b984213a"),
                            CreatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9929),
                            IsDeleted = true,
                            Name = "User 5",
                            Role = 2,
                            UpdatedAt = new DateTime(2021, 5, 24, 16, 44, 48, 528, DateTimeKind.Local).AddTicks(9931),
                            Username = "user.5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
